### ISSUE TITLE
配置路径集中管理

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/dde-file-manager-menu-oem#1]
路径为什么不设置在
~/.config/deepin/dde-file-manager/oem-menuextensions
或者
~/.local/share/deepin/dde-file-manager/oem-menuextensions

**Comment by BLumia** [comment]
这个包最初是 OEM 用的，也就是最初设计上不是给用户配置而是给应用开发者适配用的，所以先支持的是放到 `/usr/share/` 下。

可以加这个支持，也欢迎 PR ～
